-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.endereco
(
    id_endereco serial NOT NULL,
    rua character varying(250) COLLATE pg_catalog."default" NOT NULL,
    numero character varying(9) COLLATE pg_catalog."default" NOT NULL,
    bairro character varying(250) COLLATE pg_catalog."default" NOT NULL,
    cidade character varying(250) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(250) COLLATE pg_catalog."default" NOT NULL,
    cep character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT endereco_pkey PRIMARY KEY (id_endereco),
    CONSTRAINT endereco_numero_key UNIQUE (numero)
);

CREATE TABLE IF NOT EXISTS public.fornecedor
(
    id_fornecedor serial NOT NULL,
    nome character varying(250) COLLATE pg_catalog."default" NOT NULL,
    telefone integer NOT NULL,
    endereco_id integer,
    email character varying(250) COLLATE pg_catalog."default" NOT NULL,
    cnpj character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT fornecedor_pkey PRIMARY KEY (id_fornecedor)
);

CREATE TABLE IF NOT EXISTS public.movimentacao
(
    id_movimentacao serial NOT NULL,
    produto_id integer NOT NULL,
    usuario_id integer NOT NULL,
    tipo_movimentacao character varying(20) COLLATE pg_catalog."default" NOT NULL,
    quantidade integer NOT NULL,
    data_movimentacao date NOT NULL,
    CONSTRAINT movimentacao_pkey PRIMARY KEY (id_movimentacao)
);

CREATE TABLE IF NOT EXISTS public.produto
(
    id_produto serial NOT NULL,
    fornecedor_id integer,
    nome character varying(250) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default",
    quantidade integer DEFAULT 0,
    quantidade_min integer DEFAULT 0,
    tipo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    especie character varying(50) COLLATE pg_catalog."default" NOT NULL,
    dosagem character varying(50) COLLATE pg_catalog."default" NOT NULL,
    validade date NOT NULL,
    preco numeric(10, 2),
    CONSTRAINT produto_pkey PRIMARY KEY (id_produto)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id_usuario serial NOT NULL,
    nome character varying(250) COLLATE pg_catalog."default" NOT NULL,
    email character varying(250) COLLATE pg_catalog."default" NOT NULL,
    senha character varying(250) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario),
    CONSTRAINT usuario_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.fornecedor
    ADD CONSTRAINT fornecedor_endereco_id_fkey FOREIGN KEY (endereco_id)
    REFERENCES public.endereco (id_endereco) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.movimentacao
    ADD CONSTRAINT movimentacao_produto_id_fkey FOREIGN KEY (produto_id)
    REFERENCES public.produto (id_produto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.movimentacao
    ADD CONSTRAINT movimentacao_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.produto
    ADD CONSTRAINT produto_fornecedor_id_fkey FOREIGN KEY (fornecedor_id)
    REFERENCES public.fornecedor (id_fornecedor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;